import java.util.HashMap;
import java.util.Map;
import java.util.NavigableSet;
import java.util.TreeSet;

class Graph {

    // mapping of vertex names to Vertex objects, built from a set of Edges

    private final Map<String, Vertex> graph;

    /**
     * One edge of the graph (only used by Graph constructor)
     */
    public static class Edge {

        public final String v1, v2;
        public final int dist;

        public Edge(String v1, String v2, int dist) {
            this.v1 = v1;
            this.v2 = v2;
            this.dist = dist;
        }
    }

    /**
     * One vertex of the graph, complete with mappings to neighbouring vertices
     */
    public static class Vertex implements Comparable<Vertex> {

        public final String name;
        // MAX_VALUE assumed to be infinity
        public int dist = Integer.MAX_VALUE;
        public Vertex previous = null;
        public final Map<Vertex, Integer> neighbours = new HashMap<>();

        public Vertex(String name) {
            this.name = name;
        }

        private void printPath() {
            if (this == this.previous) {
                System.out.printf("%s", this.name);
            } else if (this.previous == null) {
                System.out.printf("%s(unreached)", this.name);
            } else {
                this.previous.printPath();
                System.out.printf(" -> %s(%d)", this.name, this.dist);
            }
        }

        public int compareTo(Vertex other) {
            if (dist == other.dist) {
                return name.compareTo(other.name);
            }

            return Integer.compare(dist, other.dist);
        }
        

        @Override
        public String toString() {
            return "(" + name + ", " + dist + ")";
        }
    }

    /**
     * Builds a graph from a set of edges
     */
    public Graph(Edge[] edges) {
        graph = new HashMap<>(edges.length);

        // one pass to find all vertices
        for (Edge e : edges) {
            if (!graph.containsKey(e.v1)) {
                graph.put(e.v1, new Vertex(e.v1));
            }
            if (!graph.containsKey(e.v2)) {
                graph.put(e.v2, new Vertex(e.v2));
            }
        }

        // another pass to set neighbouring vertices
        for (Edge e : edges) {
            graph.get(e.v1).neighbours.put(graph.get(e.v2), e.dist);
            // graph.get(e.v2).neighbours.put(graph.get(e.v1), e.dist); // also do this for an undirected
            // graph
        }
    }

    /**
     * Runs dijkstra using a specified source vertex
     */
    public void dijkstra(String startName) {
        if (!graph.containsKey(startName)) {
            System.err.printf(
                    "Graph doesn't contain start vertex \"%s\"%n",
                    startName
            );
            return;
        }
        final Vertex source = graph.get(startName);
        NavigableSet<Vertex> q = new TreeSet<>();

        // set-up vertices
        for (Vertex v : graph.values()) {
            v.previous = v == source ? source : null;
            v.dist = v == source ? 0 : Integer.MAX_VALUE;
            q.add(v);
        }

        dijkstra(q);
    }

    /**
     * Implementation of dijkstra's algorithm using a binary heap.
     */
    private void dijkstra(final NavigableSet<Vertex> q) {
        Vertex u, v;
        while (!q.isEmpty()) {
            // vertex with shortest distance (first iteration will return source)
            u = q.pollFirst();
            if (u.dist == Integer.MAX_VALUE) {
                break; // we can ignore u (and any other remaining vertices) since they are unreachable
            }
            // look at distances to each neighbour
            for (Map.Entry<Vertex, Integer> a : u.neighbours.entrySet()) {
                v = a.getKey(); // the neighbour in this iteration

                final int alternateDist = u.dist + a.getValue();
                if (alternateDist < v.dist) { // shorter path to neighbour found
                    q.remove(v);
                    v.dist = alternateDist;
                    v.previous = u;
                    q.add(v);
                }
            }
        }
    }

    /**
     * Prints a path from the source to the specified vertex
     */
    public void printPath(String endName) {
        if (!graph.containsKey(endName)) {
            System.err.printf(
                    "Graph doesn't contain end vertex \"%s\"%n",
                    endName
            );
            return;
        }

        graph.get(endName).printPath();
        System.out.println();
    }
    
}

class Dijkstra {
    private static final String START = "갈매";
    private static final String END = "남동구청";

    /**
     * main function Will run the code with "GRAPH" that was defined above.
     */
    public static void main(String[] args) {
        Graph g = new Graph(GRAPH);
        g.dijkstra(START);
        g.printPath(END);
        // g.printAllPaths();
    }

    private static final Graph.Edge[] GRAPH = {
            // Distance from node "a" to node "b" is 7.
            // In the current Graph there is no way to move the other way (e,g, from "b" to "a"),
            // a new edge would be needed for that

            new Graph.Edge("소요산", "동두천", 1),
            new Graph.Edge("동두천", "보산", 1),
            new Graph.Edge("보산", "동두천중앙", 1),
            new Graph.Edge("동두천중앙", "지행", 1),
            new Graph.Edge("지행", "덕정", 1),
            new Graph.Edge("덕정", "덕계", 1),
            new Graph.Edge("덕계", "양주", 1),
            new Graph.Edge("양주", "녹양", 1),
            new Graph.Edge("녹양", "가능", 1),
            new Graph.Edge("가능", "의정부", 1),
            new Graph.Edge("의정부", "회룡", 1),
            new Graph.Edge("회룡", "망월사", 1),
            new Graph.Edge("망월사", "도봉산", 1),
            new Graph.Edge("도봉산", "도봉", 1),
            new Graph.Edge("도봉", "방학", 1),
            new Graph.Edge("방학", "창동", 1),
            new Graph.Edge("창동", "녹천", 1),
            new Graph.Edge("녹천", "월계", 1),
            new Graph.Edge("월계", "광운대", 1),
            new Graph.Edge("광운대", "석계", 1),
            new Graph.Edge("석계", "신이문", 1),
            new Graph.Edge("신이문", "외대앞", 1),
            new Graph.Edge("외대앞", "회기", 1),
            new Graph.Edge("회기", "청량리", 1),
            new Graph.Edge("청량리", "제기동", 1),
            new Graph.Edge("제기동", "신설동", 1),
            new Graph.Edge("신설동", "동묘앞", 1),
            new Graph.Edge("동묘앞", "동대문", 1),
            new Graph.Edge("동대문", "종로5가", 1),
            new Graph.Edge("종로5가", "종로3가", 1),
            new Graph.Edge("종로3가", "종각", 1),
            new Graph.Edge("종각", "시청", 1),
            new Graph.Edge("시청", "서울역", 1),
            new Graph.Edge("서울역", "남영", 1),
            new Graph.Edge("남영", "용산", 1),
            new Graph.Edge("용산", "노량진", 1),
            new Graph.Edge("노량진", "대방", 1),
            new Graph.Edge("대방", "신길", 1),
            new Graph.Edge("신길", "영등포", 1),
            new Graph.Edge("영등포", "신도림", 1),
            new Graph.Edge("신도림", "구로", 1),
            new Graph.Edge("구로", "구일", 1),
            new Graph.Edge("구일", "개봉", 1),
            new Graph.Edge("개봉", "오류동", 1),
            new Graph.Edge("오류동", "온수", 1),
            new Graph.Edge("온수", "역곡", 1),
            new Graph.Edge("역곡", "소사", 1),
            new Graph.Edge("소사", "부천", 1),
            new Graph.Edge("부천", "중동", 1),
            new Graph.Edge("중동", "송내", 1),
            new Graph.Edge("송내", "부개", 1),
            new Graph.Edge("부개", "부평", 1),
            new Graph.Edge("부평", "백운", 1),
            new Graph.Edge("백운", "동암", 1),
            new Graph.Edge("동암", "간석", 1),
            new Graph.Edge("간석", "주안", 1),
            new Graph.Edge("주안", "도화", 1),
            new Graph.Edge("도화", "제물포", 1),
            new Graph.Edge("제물포", "도원", 1),
            new Graph.Edge("도원", "동인천", 1),
            new Graph.Edge("동인천", "인천", 1),
            new Graph.Edge("구로", "가산디지털단지", 1),
            new Graph.Edge("가산디지털단지", "독산", 1),
            new Graph.Edge("독산", "금천구청", 1),
            new Graph.Edge("금천구청", "광명", 1),
            new Graph.Edge("금천구청", "석수", 1),
            new Graph.Edge("석수", "관악", 1),
            new Graph.Edge("관악", "안양", 1),
            new Graph.Edge("안양", "명학", 1),
            new Graph.Edge("명학", "금정", 1),
            new Graph.Edge("금정", "군포", 1),
            new Graph.Edge("군포", "당정", 1),
            new Graph.Edge("당정", "의왕", 1),
            new Graph.Edge("의왕", "성균관대", 1),
            new Graph.Edge("성균관대", "화서", 1),
            new Graph.Edge("화서", "수원", 1),
            new Graph.Edge("수원", "세류", 1),
            new Graph.Edge("세류", "병점", 1),
            new Graph.Edge("병점", "서동탄", 1),
            new Graph.Edge("병점", "세마", 1),
            new Graph.Edge("세마", "오산대", 1),
            new Graph.Edge("오산대", "오산", 1),
            new Graph.Edge("오산", "진위", 1),
            new Graph.Edge("진위", "송탄", 1),
            new Graph.Edge("송탄", "서정리", 1),
            new Graph.Edge("서정리", "평택지제", 1),
            new Graph.Edge("평택지제", "평택", 1),
            new Graph.Edge("평택", "성환", 1),
            new Graph.Edge("성환", "직산", 1),
            new Graph.Edge("직산", "두정", 1),
            new Graph.Edge("두정", "천안", 1),
            new Graph.Edge("천안", "봉명", 1),
            new Graph.Edge("봉명", "쌍용", 1),
            new Graph.Edge("쌍용", "아산", 1),
            new Graph.Edge("아산", "탕정", 1),
            new Graph.Edge("탕정", "배방", 1),
            new Graph.Edge("배방", "온양온천", 1),
            new Graph.Edge("온양온천", "신창", 1),
            new Graph.Edge("신창", "아산", 1),
            new Graph.Edge("아산", "탕정", 1),
            new Graph.Edge("탕정", "배방", 1),
            new Graph.Edge("배방", "온양온천", 1),
            new Graph.Edge("온양온천", "신창", 1),
            new Graph.Edge("동두천", "소요산", 1),
            new Graph.Edge("보산", "동두천", 1),
            new Graph.Edge("동두천중앙", "보산", 1),
            new Graph.Edge("지행", "동두천중앙", 1),
            new Graph.Edge("덕정", "지행", 1),
            new Graph.Edge("덕계", "덕정", 1),
            new Graph.Edge("양주", "덕계", 1),
            new Graph.Edge("녹양", "양주", 1),
            new Graph.Edge("가능", "녹양", 1),
            new Graph.Edge("의정부", "가능", 1),
            new Graph.Edge("회룡", "의정부", 1),
            new Graph.Edge("망월사", "회룡", 1),
            new Graph.Edge("도봉산", "망월사", 1),
            new Graph.Edge("도봉", "도봉산", 1),
            new Graph.Edge("방학", "도봉", 1),
            new Graph.Edge("창동", "방학", 1),
            new Graph.Edge("녹천", "창동", 1),
            new Graph.Edge("월계", "녹천", 1),
            new Graph.Edge("광운대", "월계", 1),
            new Graph.Edge("석계", "광운대", 1),
            new Graph.Edge("신이문", "석계", 1),
            new Graph.Edge("외대앞", "신이문", 1),
            new Graph.Edge("회기", "외대앞", 1),
            new Graph.Edge("청량리", "회기", 1),
            new Graph.Edge("제기동", "청량리", 1),
            new Graph.Edge("신설동", "제기동", 1),
            new Graph.Edge("동묘앞", "신설동", 1),
            new Graph.Edge("동대문", "동묘앞", 1),
            new Graph.Edge("종로5가", "동대문", 1),
            new Graph.Edge("종로3가", "종로5가", 1),
            new Graph.Edge("종각", "종로3가", 1),
            new Graph.Edge("시청", "종각", 1),
            new Graph.Edge("서울역", "시청", 1),
            new Graph.Edge("남영", "서울역", 1),
            new Graph.Edge("용산", "남영", 1),
            new Graph.Edge("노량진", "용산", 1),
            new Graph.Edge("대방", "노량진", 1),
            new Graph.Edge("신길", "대방", 1),
            new Graph.Edge("영등포", "신길", 1),
            new Graph.Edge("신도림", "영등포", 1),
            new Graph.Edge("구로", "신도림", 1),
            new Graph.Edge("구일", "구로", 1),
            new Graph.Edge("개봉", "구일", 1),
            new Graph.Edge("오류동", "개봉", 1),
            new Graph.Edge("온수", "오류동", 1),
            new Graph.Edge("역곡", "온수", 1),
            new Graph.Edge("소사", "역곡", 1),
            new Graph.Edge("부천", "소사", 1),
            new Graph.Edge("중동", "부천", 1),
            new Graph.Edge("송내", "중동", 1),
            new Graph.Edge("부개", "송내", 1),
            new Graph.Edge("부평", "부개", 1),
            new Graph.Edge("백운", "부평", 1),
            new Graph.Edge("동암", "백운", 1),
            new Graph.Edge("간석", "동암", 1),
            new Graph.Edge("주안", "간석", 1),
            new Graph.Edge("도화", "주안", 1),
            new Graph.Edge("제물포", "도화", 1),
            new Graph.Edge("도원", "제물포", 1),
            new Graph.Edge("동인천", "도원", 1),
            new Graph.Edge("인천", "동인천", 1),
            new Graph.Edge("가산디지털단지", "구로", 1),
            new Graph.Edge("독산", "가산디지털단지", 1),
            new Graph.Edge("금천구청", "독산", 1),
            new Graph.Edge("광명", "금천구청", 1),
            new Graph.Edge("석수", "금천구청", 1),
            new Graph.Edge("관악", "석수", 1),
            new Graph.Edge("안양", "관악", 1),
            new Graph.Edge("명학", "안양", 1),
            new Graph.Edge("금정", "명학", 1),
            new Graph.Edge("군포", "금정", 1),
            new Graph.Edge("당정", "군포", 1),
            new Graph.Edge("의왕", "당정", 1),
            new Graph.Edge("성균관대", "의왕", 1),
            new Graph.Edge("화서", "성균관대", 1),
            new Graph.Edge("수원", "화서", 1),
            new Graph.Edge("세류", "수원", 1),
            new Graph.Edge("병점", "세류", 1),
            new Graph.Edge("서동탄", "병점", 1),
            new Graph.Edge("세마", "병점", 1),
            new Graph.Edge("오산대", "세마", 1),
            new Graph.Edge("오산", "오산대", 1),
            new Graph.Edge("진위", "오산", 1),
            new Graph.Edge("송탄", "진위", 1),
            new Graph.Edge("서정리", "송탄", 1),
            new Graph.Edge("평택지제", "서정리", 1),
            new Graph.Edge("평택", "평택지제", 1),
            new Graph.Edge("성환", "평택", 1),
            new Graph.Edge("직산", "성환", 1),
            new Graph.Edge("두정", "직산", 1),
            new Graph.Edge("천안", "두정", 1),
            new Graph.Edge("봉명", "천안", 1),
            new Graph.Edge("쌍용", "봉명", 1),
            new Graph.Edge("아산", "쌍용", 1),
            new Graph.Edge("탕정", "아산", 1),
            new Graph.Edge("배방", "탕정", 1),
            new Graph.Edge("온양온천", "배방", 1),
            new Graph.Edge("신창", "온양온천", 1),
            new Graph.Edge("아산", "신창", 1),
            new Graph.Edge("탕정", "아산", 1),
            new Graph.Edge("배방", "탕정", 1),
            new Graph.Edge("온양온천", "배방", 1),
            new Graph.Edge("신창", "온양온천", 1),
            new Graph.Edge("시청", "을지로입구", 1),
            new Graph.Edge("을지로입구", "을지로3가", 1),
            new Graph.Edge("을지로3가", "을지로4가", 1),
            new Graph.Edge("을지로4가", "동대문역사문화공원", 1),
            new Graph.Edge("동대문역사문화공원", "신당", 1),
            new Graph.Edge("신당", "상왕십리", 1),
            new Graph.Edge("상왕십리", "왕십리", 1),
            new Graph.Edge("왕십리", "한양대", 1),
            new Graph.Edge("한양대", "뚝섬", 1),
            new Graph.Edge("뚝섬", "성수", 1),
            new Graph.Edge("성수", "건대입구", 1),
            new Graph.Edge("건대입구", "구의", 1),
            new Graph.Edge("구의", "강변", 1),
            new Graph.Edge("강변", "잠실나루", 1),
            new Graph.Edge("잠실나루", "잠실", 1),
            new Graph.Edge("잠실", "잠실새내", 1),
            new Graph.Edge("잠실새내", "종합운동장", 1),
            new Graph.Edge("종합운동장", "삼성", 1),
            new Graph.Edge("삼성", "선릉", 1),
            new Graph.Edge("선릉", "역삼", 1),
            new Graph.Edge("역삼", "강남", 1),
            new Graph.Edge("강남", "교대", 1),
            new Graph.Edge("교대", "서초", 1),
            new Graph.Edge("서초", "방배", 1),
            new Graph.Edge("방배", "사당", 1),
            new Graph.Edge("사당", "낙성대", 1),
            new Graph.Edge("낙성대", "서울대입구", 1),
            new Graph.Edge("서울대입구", "봉천", 1),
            new Graph.Edge("봉천", "신림", 1),
            new Graph.Edge("신림", "신대방", 1),
            new Graph.Edge("신대방", "구로디지털단지", 1),
            new Graph.Edge("구로디지털단지", "대림", 1),
            new Graph.Edge("대림", "신도림", 1),
            new Graph.Edge("신도림", "문래", 1),
            new Graph.Edge("문래", "영등포구청", 1),
            new Graph.Edge("영등포구청", "당산", 1),
            new Graph.Edge("당산", "합정", 1),
            new Graph.Edge("합정", "홍대입구", 1),
            new Graph.Edge("홍대입구", "신촌", 1),
            new Graph.Edge("신촌", "이대", 1),
            new Graph.Edge("이대", "아현", 1),
            new Graph.Edge("아현", "충정로", 1),
            new Graph.Edge("충정로", "시청", 1),
            new Graph.Edge("성수", "용답", 1),
            new Graph.Edge("용답", "신답", 1),
            new Graph.Edge("신답", "용두", 1),
            new Graph.Edge("용두", "신설동", 1),
            new Graph.Edge("신도림", "도림천", 1),
            new Graph.Edge("도림천", "양천구청", 1),
            new Graph.Edge("양천구청", "신정네거리", 1),
            new Graph.Edge("신정네거리", "까치산", 1),
            new Graph.Edge("을지로입구", "시청", 1),
            new Graph.Edge("을지로3가", "을지로입구", 1),
            new Graph.Edge("을지로4가", "을지로3가", 1),
            new Graph.Edge("동대문역사문화공원", "을지로4가", 1),
            new Graph.Edge("신당", "동대문역사문화공원", 1),
            new Graph.Edge("상왕십리", "신당", 1),
            new Graph.Edge("왕십리", "상왕십리", 1),
            new Graph.Edge("한양대", "왕십리", 1),
            new Graph.Edge("뚝섬", "한양대", 1),
            new Graph.Edge("성수", "뚝섬", 1),
            new Graph.Edge("건대입구", "성수", 1),
            new Graph.Edge("구의", "건대입구", 1),
            new Graph.Edge("강변", "구의", 1),
            new Graph.Edge("잠실나루", "강변", 1),
            new Graph.Edge("잠실", "잠실나루", 1),
            new Graph.Edge("잠실새내", "잠실", 1),
            new Graph.Edge("종합운동장", "잠실새내", 1),
            new Graph.Edge("삼성", "종합운동장", 1),
            new Graph.Edge("선릉", "삼성", 1),
            new Graph.Edge("역삼", "선릉", 1),
            new Graph.Edge("강남", "역삼", 1),
            new Graph.Edge("교대", "강남", 1),
            new Graph.Edge("서초", "교대", 1),
            new Graph.Edge("방배", "서초", 1),
            new Graph.Edge("사당", "방배", 1),
            new Graph.Edge("낙성대", "사당", 1),
            new Graph.Edge("서울대입구", "낙성대", 1),
            new Graph.Edge("봉천", "서울대입구", 1),
            new Graph.Edge("신림", "봉천", 1),
            new Graph.Edge("신대방", "신림", 1),
            new Graph.Edge("구로디지털단지", "신대방", 1),
            new Graph.Edge("대림", "구로디지털단지", 1),
            new Graph.Edge("신도림", "대림", 1),
            new Graph.Edge("문래", "신도림", 1),
            new Graph.Edge("영등포구청", "문래", 1),
            new Graph.Edge("당산", "영등포구청", 1),
            new Graph.Edge("합정", "당산", 1),
            new Graph.Edge("홍대입구", "합정", 1),
            new Graph.Edge("신촌", "홍대입구", 1),
            new Graph.Edge("이대", "신촌", 1),
            new Graph.Edge("아현", "이대", 1),
            new Graph.Edge("충정로", "아현", 1),
            new Graph.Edge("시청", "충정로", 1),
            new Graph.Edge("용답", "성수", 1),
            new Graph.Edge("신답", "용답", 1),
            new Graph.Edge("용두", "신답", 1),
            new Graph.Edge("신설동", "용두", 1),
            new Graph.Edge("도림천", "신도림", 1),
            new Graph.Edge("양천구청", "도림천", 1),
            new Graph.Edge("신정네거리", "양천구청", 1),
            new Graph.Edge("까치산", "신정네거리", 1),
            new Graph.Edge("대화", "주엽", 1),
            new Graph.Edge("주엽", "정발산", 1),
            new Graph.Edge("정발산", "마두", 1),
            new Graph.Edge("마두", "백석", 1),
            new Graph.Edge("백석", "대곡", 1),
            new Graph.Edge("대곡", "화정", 1),
            new Graph.Edge("화정", "원당", 1),
            new Graph.Edge("원당", "원흥", 1),
            new Graph.Edge("원흥", "삼송", 1),
            new Graph.Edge("삼송", "지축", 1),
            new Graph.Edge("지축", "구파발", 1),
            new Graph.Edge("구파발", "연신내", 1),
            new Graph.Edge("연신내", "불광", 1),
            new Graph.Edge("불광", "녹번", 1),
            new Graph.Edge("녹번", "홍제", 1),
            new Graph.Edge("홍제", "무악재", 1),
            new Graph.Edge("무악재", "독립문", 1),
            new Graph.Edge("독립문", "경복궁", 1),
            new Graph.Edge("경복궁", "안국", 1),
            new Graph.Edge("안국", "종로3가", 1),
            new Graph.Edge("종로3가", "을지로3가", 1),
            new Graph.Edge("을지로3가", "충무로", 1),
            new Graph.Edge("충무로", "동대입구", 1),
            new Graph.Edge("동대입구", "약수", 1),
            new Graph.Edge("약수", "금호", 1),
            new Graph.Edge("금호", "옥수", 1),
            new Graph.Edge("옥수", "압구정", 1),
            new Graph.Edge("압구정", "신사", 1),
            new Graph.Edge("신사", "잠원", 1),
            new Graph.Edge("잠원", "고속터미널", 1),
            new Graph.Edge("고속터미널", "교대", 1),
            new Graph.Edge("교대", "남부터미널", 1),
            new Graph.Edge("남부터미널", "양재", 1),
            new Graph.Edge("양재", "매봉", 1),
            new Graph.Edge("매봉", "도곡", 1),
            new Graph.Edge("도곡", "대치", 1),
            new Graph.Edge("대치", "학여울", 1),
            new Graph.Edge("학여울", "대청", 1),
            new Graph.Edge("대청", "일원", 1),
            new Graph.Edge("일원", "수서", 1),
            new Graph.Edge("수서", "가락시장", 1),
            new Graph.Edge("가락시장", "경찰병원", 1),
            new Graph.Edge("경찰병원", "오금", 1),
            new Graph.Edge("주엽", "대화", 1),
            new Graph.Edge("정발산", "주엽", 1),
            new Graph.Edge("마두", "정발산", 1),
            new Graph.Edge("백석", "마두", 1),
            new Graph.Edge("대곡", "백석", 1),
            new Graph.Edge("화정", "대곡", 1),
            new Graph.Edge("원당", "화정", 1),
            new Graph.Edge("원흥", "원당", 1),
            new Graph.Edge("삼송", "원흥", 1),
            new Graph.Edge("지축", "삼송", 1),
            new Graph.Edge("구파발", "지축", 1),
            new Graph.Edge("연신내", "구파발", 1),
            new Graph.Edge("불광", "연신내", 1),
            new Graph.Edge("녹번", "불광", 1),
            new Graph.Edge("홍제", "녹번", 1),
            new Graph.Edge("무악재", "홍제", 1),
            new Graph.Edge("독립문", "무악재", 1),
            new Graph.Edge("경복궁", "독립문", 1),
            new Graph.Edge("안국", "경복궁", 1),
            new Graph.Edge("종로3가", "안국", 1),
            new Graph.Edge("을지로3가", "종로3가", 1),
            new Graph.Edge("충무로", "을지로3가", 1),
            new Graph.Edge("동대입구", "충무로", 1),
            new Graph.Edge("약수", "동대입구", 1),
            new Graph.Edge("금호", "약수", 1),
            new Graph.Edge("옥수", "금호", 1),
            new Graph.Edge("압구정", "옥수", 1),
            new Graph.Edge("신사", "압구정", 1),
            new Graph.Edge("잠원", "신사", 1),
            new Graph.Edge("고속터미널", "잠원", 1),
            new Graph.Edge("교대", "고속터미널", 1),
            new Graph.Edge("남부터미널", "교대", 1),
            new Graph.Edge("양재", "남부터미널", 1),
            new Graph.Edge("매봉", "양재", 1),
            new Graph.Edge("도곡", "매봉", 1),
            new Graph.Edge("대치", "도곡", 1),
            new Graph.Edge("학여울", "대치", 1),
            new Graph.Edge("대청", "학여울", 1),
            new Graph.Edge("일원", "대청", 1),
            new Graph.Edge("수서", "일원", 1),
            new Graph.Edge("가락시장", "수서", 1),
            new Graph.Edge("경찰병원", "가락시장", 1),
            new Graph.Edge("오금", "경찰병원", 1),
            new Graph.Edge("진접", "오남", 1),
            new Graph.Edge("오남", "별내별가람", 1),
            new Graph.Edge("별내별가람", "당고개", 1),
            new Graph.Edge("당고개", "상계", 1),
            new Graph.Edge("상계", "노원", 1),
            new Graph.Edge("노원", "창동", 1),
            new Graph.Edge("창동", "쌍문", 1),
            new Graph.Edge("쌍문", "수유", 1),
            new Graph.Edge("수유", "미아", 1),
            new Graph.Edge("미아", "미아사거리", 1),
            new Graph.Edge("미아사거리", "길음", 1),
            new Graph.Edge("길음", "성신여대입구", 1),
            new Graph.Edge("성신여대입구", "한성대입구", 1),
            new Graph.Edge("한성대입구", "혜화", 1),
            new Graph.Edge("혜화", "동대문", 1),
            new Graph.Edge("동대문", "동대문역사문화공원", 1),
            new Graph.Edge("동대문역사문화공원", "충무로", 1),
            new Graph.Edge("충무로", "명동", 1),
            new Graph.Edge("명동", "회현", 1),
            new Graph.Edge("회현", "서울역", 1),
            new Graph.Edge("서울역", "숙대입구", 1),
            new Graph.Edge("숙대입구", "삼각지", 1),
            new Graph.Edge("삼각지", "신용산", 1),
            new Graph.Edge("신용산", "이촌", 1),
            new Graph.Edge("이촌", "동작", 1),
            new Graph.Edge("동작", "총신대입구", 1),
            new Graph.Edge("총신대입구", "사당", 1),
            new Graph.Edge("사당", "남태령", 1),
            new Graph.Edge("남태령", "선바위", 1),
            new Graph.Edge("선바위", "경마공원", 1),
            new Graph.Edge("경마공원", "대공원", 1),
            new Graph.Edge("대공원", "과천", 1),
            new Graph.Edge("과천", "정부과천청사", 1),
            new Graph.Edge("정부과천청사", "인덕원", 1),
            new Graph.Edge("인덕원", "평촌", 1),
            new Graph.Edge("평촌", "범계", 1),
            new Graph.Edge("범계", "금정", 1),
            new Graph.Edge("금정", "산본", 1),
            new Graph.Edge("산본", "수리산", 1),
            new Graph.Edge("수리산", "대야미", 1),
            new Graph.Edge("대야미", "반월", 1),
            new Graph.Edge("반월", "상록수", 1),
            new Graph.Edge("상록수", "한대앞", 1),
            new Graph.Edge("한대앞", "중앙", 1),
            new Graph.Edge("중앙", "고잔", 1),
            new Graph.Edge("고잔", "초지", 1),
            new Graph.Edge("초지", "안산", 1),
            new Graph.Edge("안산", "신길온천", 1),
            new Graph.Edge("신길온천", "정왕", 1),
            new Graph.Edge("정왕", "오이도", 1),
            new Graph.Edge("오남", "진접", 1),
            new Graph.Edge("별내별가람", "오남", 1),
            new Graph.Edge("당고개", "별내별가람", 1),
            new Graph.Edge("상계", "당고개", 1),
            new Graph.Edge("노원", "상계", 1),
            new Graph.Edge("창동", "노원", 1),
            new Graph.Edge("쌍문", "창동", 1),
            new Graph.Edge("수유", "쌍문", 1),
            new Graph.Edge("미아", "수유", 1),
            new Graph.Edge("미아사거리", "미아", 1),
            new Graph.Edge("길음", "미아사거리", 1),
            new Graph.Edge("성신여대입구", "길음", 1),
            new Graph.Edge("한성대입구", "성신여대입구", 1),
            new Graph.Edge("혜화", "한성대입구", 1),
            new Graph.Edge("동대문", "혜화", 1),
            new Graph.Edge("동대문역사문화공원", "동대문", 1),
            new Graph.Edge("충무로", "동대문역사문화공원", 1),
            new Graph.Edge("명동", "충무로", 1),
            new Graph.Edge("회현", "명동", 1),
            new Graph.Edge("서울역", "회현", 1),
            new Graph.Edge("숙대입구", "서울역", 1),
            new Graph.Edge("삼각지", "숙대입구", 1),
            new Graph.Edge("신용산", "삼각지", 1),
            new Graph.Edge("이촌", "신용산", 1),
            new Graph.Edge("동작", "이촌", 1),
            new Graph.Edge("총신대입구", "동작", 1),
            new Graph.Edge("사당", "총신대입구", 1),
            new Graph.Edge("남태령", "사당", 1),
            new Graph.Edge("선바위", "남태령", 1),
            new Graph.Edge("경마공원", "선바위", 1),
            new Graph.Edge("대공원", "경마공원", 1),
            new Graph.Edge("과천", "대공원", 1),
            new Graph.Edge("정부과천청사", "과천", 1),
            new Graph.Edge("인덕원", "정부과천청사", 1),
            new Graph.Edge("평촌", "인덕원", 1),
            new Graph.Edge("범계", "평촌", 1),
            new Graph.Edge("금정", "범계", 1),
            new Graph.Edge("산본", "금정", 1),
            new Graph.Edge("수리산", "산본", 1),
            new Graph.Edge("대야미", "수리산", 1),
            new Graph.Edge("반월", "대야미", 1),
            new Graph.Edge("상록수", "반월", 1),
            new Graph.Edge("한대앞", "상록수", 1),
            new Graph.Edge("중앙", "한대앞", 1),
            new Graph.Edge("고잔", "중앙", 1),
            new Graph.Edge("초지", "고잔", 1),
            new Graph.Edge("안산", "초지", 1),
            new Graph.Edge("신길온천", "안산", 1),
            new Graph.Edge("정왕", "신길온천", 1),
            new Graph.Edge("오이도", "정왕", 1),
            new Graph.Edge("방화", "개화산", 1),
            new Graph.Edge("개화산", "김포공항", 1),
            new Graph.Edge("김포공항", "송정", 1),
            new Graph.Edge("송정", "마곡", 1),
            new Graph.Edge("마곡", "발산", 1),
            new Graph.Edge("발산", "우장산", 1),
            new Graph.Edge("우장산", "화곡", 1),
            new Graph.Edge("화곡", "까치산", 1),
            new Graph.Edge("까치산", "신정", 1),
            new Graph.Edge("신정", "목동", 1),
            new Graph.Edge("목동", "오목교", 1),
            new Graph.Edge("오목교", "양평", 1),
            new Graph.Edge("양평", "영등포구청", 1),
            new Graph.Edge("영등포구청", "영등포시장", 1),
            new Graph.Edge("영등포시장", "신길", 1),
            new Graph.Edge("신길", "여의도", 1),
            new Graph.Edge("여의도", "여의나루", 1),
            new Graph.Edge("여의나루", "마포", 1),
            new Graph.Edge("마포", "공덕", 1),
            new Graph.Edge("공덕", "애오개", 1),
            new Graph.Edge("애오개", "충정로", 1),
            new Graph.Edge("충정로", "서대문", 1),
            new Graph.Edge("서대문", "광화문", 1),
            new Graph.Edge("광화문", "종로3가", 1),
            new Graph.Edge("종로3가", "을지로4가", 1),
            new Graph.Edge("을지로4가", "동대문역사문화공원", 1),
            new Graph.Edge("동대문역사문화공원", "청구", 1),
            new Graph.Edge("청구", "신금호", 1),
            new Graph.Edge("신금호", "행당", 1),
            new Graph.Edge("행당", "왕십리", 1),
            new Graph.Edge("왕십리", "마장", 1),
            new Graph.Edge("마장", "답십리", 1),
            new Graph.Edge("답십리", "장한평", 1),
            new Graph.Edge("장한평", "군자", 1),
            new Graph.Edge("군자", "아차산", 1),
            new Graph.Edge("아차산", "광나루", 1),
            new Graph.Edge("광나루", "천호", 1),
            new Graph.Edge("천호", "강동", 1),
            new Graph.Edge("강동", "길동", 1),
            new Graph.Edge("길동", "굽은다리", 1),
            new Graph.Edge("굽은다리", "명일", 1),
            new Graph.Edge("명일", "고덕", 1),
            new Graph.Edge("고덕", "상일동", 1),
            new Graph.Edge("상일동", "강일", 1),
            new Graph.Edge("강일", "미사", 1),
            new Graph.Edge("미사", "하남풍산", 1),
            new Graph.Edge("하남풍산", "하남시청", 1),
            new Graph.Edge("하남시청", "하남검단산", 1),
            new Graph.Edge("강동", "둔촌동", 1),
            new Graph.Edge("둔촌동", "올림픽공원", 1),
            new Graph.Edge("올림픽공원", "방이", 1),
            new Graph.Edge("방이", "오금", 1),
            new Graph.Edge("오금", "개롱", 1),
            new Graph.Edge("개롱", "거여", 1),
            new Graph.Edge("거여", "마천", 1),
            new Graph.Edge("개화산", "방화", 1),
            new Graph.Edge("김포공항", "개화산", 1),
            new Graph.Edge("송정", "김포공항", 1),
            new Graph.Edge("마곡", "송정", 1),
            new Graph.Edge("발산", "마곡", 1),
            new Graph.Edge("우장산", "발산", 1),
            new Graph.Edge("화곡", "우장산", 1),
            new Graph.Edge("까치산", "화곡", 1),
            new Graph.Edge("신정", "까치산", 1),
            new Graph.Edge("목동", "신정", 1),
            new Graph.Edge("오목교", "목동", 1),
            new Graph.Edge("양평", "오목교", 1),
            new Graph.Edge("영등포구청", "양평", 1),
            new Graph.Edge("영등포시장", "영등포구청", 1),
            new Graph.Edge("신길", "영등포시장", 1),
            new Graph.Edge("여의도", "신길", 1),
            new Graph.Edge("여의나루", "여의도", 1),
            new Graph.Edge("마포", "여의나루", 1),
            new Graph.Edge("공덕", "마포", 1),
            new Graph.Edge("애오개", "공덕", 1),
            new Graph.Edge("충정로", "애오개", 1),
            new Graph.Edge("서대문", "충정로", 1),
            new Graph.Edge("광화문", "서대문", 1),
            new Graph.Edge("종로3가", "광화문", 1),
            new Graph.Edge("을지로4가", "종로3가", 1),
            new Graph.Edge("동대문역사문화공원", "을지로4가", 1),
            new Graph.Edge("청구", "동대문역사문화공원", 1),
            new Graph.Edge("신금호", "청구", 1),
            new Graph.Edge("행당", "신금호", 1),
            new Graph.Edge("왕십리", "행당", 1),
            new Graph.Edge("마장", "왕십리", 1),
            new Graph.Edge("답십리", "마장", 1),
            new Graph.Edge("장한평", "답십리", 1),
            new Graph.Edge("군자", "장한평", 1),
            new Graph.Edge("아차산", "군자", 1),
            new Graph.Edge("광나루", "아차산", 1),
            new Graph.Edge("천호", "광나루", 1),
            new Graph.Edge("강동", "천호", 1),
            new Graph.Edge("길동", "강동", 1),
            new Graph.Edge("굽은다리", "길동", 1),
            new Graph.Edge("명일", "굽은다리", 1),
            new Graph.Edge("고덕", "명일", 1),
            new Graph.Edge("상일동", "고덕", 1),
            new Graph.Edge("강일", "상일동", 1),
            new Graph.Edge("미사", "강일", 1),
            new Graph.Edge("하남풍산", "미사", 1),
            new Graph.Edge("하남시청", "하남풍산", 1),
            new Graph.Edge("하남검단산", "하남시청", 1),
            new Graph.Edge("둔촌동", "강동", 1),
            new Graph.Edge("올림픽공원", "둔촌동", 1),
            new Graph.Edge("방이", "올림픽공원", 1),
            new Graph.Edge("오금", "방이", 1),
            new Graph.Edge("개롱", "오금", 1),
            new Graph.Edge("거여", "개롱", 1),
            new Graph.Edge("마천", "거여", 1),
            new Graph.Edge("응암", "역촌", 1),
            new Graph.Edge("역촌", "불광", 1),
            new Graph.Edge("불광", "독바위", 1),
            new Graph.Edge("독바위", "연신내", 1),
            new Graph.Edge("연신내", "구산", 1),
            new Graph.Edge("구산", "응암", 1),
            new Graph.Edge("응암", "새절", 1),
            new Graph.Edge("새절", "증산", 1),
            new Graph.Edge("증산", "디지털미디어시티", 1),
            new Graph.Edge("디지털미디어시티", "월드컵경기장", 1),
            new Graph.Edge("월드컵경기장", "마포구청", 1),
            new Graph.Edge("마포구청", "망원", 1),
            new Graph.Edge("망원", "합정", 1),
            new Graph.Edge("합정", "상수", 1),
            new Graph.Edge("상수", "광흥창", 1),
            new Graph.Edge("광흥창", "대흥", 1),
            new Graph.Edge("대흥", "공덕", 1),
            new Graph.Edge("공덕", "효창공원앞", 1),
            new Graph.Edge("효창공원앞", "삼각지", 1),
            new Graph.Edge("삼각지", "녹사평", 1),
            new Graph.Edge("녹사평", "이태원", 1),
            new Graph.Edge("이태원", "한강진", 1),
            new Graph.Edge("한강진", "버티고개", 1),
            new Graph.Edge("버티고개", "약수", 1),
            new Graph.Edge("약수", "청구", 1),
            new Graph.Edge("청구", "신당", 1),
            new Graph.Edge("신당", "동묘앞", 1),
            new Graph.Edge("동묘앞", "창신", 1),
            new Graph.Edge("창신", "보문", 1),
            new Graph.Edge("보문", "안암", 1),
            new Graph.Edge("안암", "고려대", 1),
            new Graph.Edge("고려대", "월곡", 1),
            new Graph.Edge("월곡", "상월곡", 1),
            new Graph.Edge("상월곡", "돌곶이", 1),
            new Graph.Edge("돌곶이", "석계", 1),
            new Graph.Edge("석계", "태릉입구", 1),
            new Graph.Edge("태릉입구", "화랑대", 1),
            new Graph.Edge("화랑대", "봉화산", 1),
            new Graph.Edge("봉화산", "신내", 1),
            new Graph.Edge("역촌", "응암", 1),
            new Graph.Edge("불광", "역촌", 1),
            new Graph.Edge("독바위", "불광", 1),
            new Graph.Edge("연신내", "독바위", 1),
            new Graph.Edge("구산", "연신내", 1),
            new Graph.Edge("응암", "구산", 1),
            new Graph.Edge("새절", "응암", 1),
            new Graph.Edge("증산", "새절", 1),
            new Graph.Edge("디지털미디어시티", "증산", 1),
            new Graph.Edge("월드컵경기장", "디지털미디어시티", 1),
            new Graph.Edge("마포구청", "월드컵경기장", 1),
            new Graph.Edge("망원", "마포구청", 1),
            new Graph.Edge("합정", "망원", 1),
            new Graph.Edge("상수", "합정", 1),
            new Graph.Edge("광흥창", "상수", 1),
            new Graph.Edge("대흥", "광흥창", 1),
            new Graph.Edge("공덕", "대흥", 1),
            new Graph.Edge("효창공원앞", "공덕", 1),
            new Graph.Edge("삼각지", "효창공원앞", 1),
            new Graph.Edge("녹사평", "삼각지", 1),
            new Graph.Edge("이태원", "녹사평", 1),
            new Graph.Edge("한강진", "이태원", 1),
            new Graph.Edge("버티고개", "한강진", 1),
            new Graph.Edge("약수", "버티고개", 1),
            new Graph.Edge("청구", "약수", 1),
            new Graph.Edge("신당", "청구", 1),
            new Graph.Edge("동묘앞", "신당", 1),
            new Graph.Edge("창신", "동묘앞", 1),
            new Graph.Edge("보문", "창신", 1),
            new Graph.Edge("안암", "보문", 1),
            new Graph.Edge("고려대", "안암", 1),
            new Graph.Edge("월곡", "고려대", 1),
            new Graph.Edge("상월곡", "월곡", 1),
            new Graph.Edge("돌곶이", "상월곡", 1),
            new Graph.Edge("석계", "돌곶이", 1),
            new Graph.Edge("태릉입구", "석계", 1),
            new Graph.Edge("화랑대", "태릉입구", 1),
            new Graph.Edge("봉화산", "화랑대", 1),
            new Graph.Edge("신내", "봉화산", 1),
            new Graph.Edge("장암", "도봉산", 1),
            new Graph.Edge("도봉산", "수락산", 1),
            new Graph.Edge("수락산", "마들", 1),
            new Graph.Edge("마들", "노원", 1),
            new Graph.Edge("노원", "중계", 1),
            new Graph.Edge("중계", "하계", 1),
            new Graph.Edge("하계", "공릉", 1),
            new Graph.Edge("공릉", "태릉입구", 1),
            new Graph.Edge("태릉입구", "먹골", 1),
            new Graph.Edge("먹골", "중화", 1),
            new Graph.Edge("중화", "상봉", 1),
            new Graph.Edge("상봉", "면목", 1),
            new Graph.Edge("면목", "사가정", 1),
            new Graph.Edge("사가정", "용마산", 1),
            new Graph.Edge("용마산", "중곡", 1),
            new Graph.Edge("중곡", "군자", 1),
            new Graph.Edge("군자", "어린이대공원", 1),
            new Graph.Edge("어린이대공원", "건대입구", 1),
            new Graph.Edge("건대입구", "뚝섬유원지", 1),
            new Graph.Edge("뚝섬유원지", "청담", 1),
            new Graph.Edge("청담", "강남구청", 1),
            new Graph.Edge("강남구청", "학동", 1),
            new Graph.Edge("학동", "논현", 1),
            new Graph.Edge("논현", "반포", 1),
            new Graph.Edge("반포", "고속터미널", 1),
            new Graph.Edge("고속터미널", "내방", 1),
            new Graph.Edge("내방", "이수", 1),
            new Graph.Edge("이수", "남성", 1),
            new Graph.Edge("남성", "숭실대입구", 1),
            new Graph.Edge("숭실대입구", "상도", 1),
            new Graph.Edge("상도", "장승배기", 1),
            new Graph.Edge("장승배기", "신대방삼거리", 1),
            new Graph.Edge("신대방삼거리", "보라매", 1),
            new Graph.Edge("보라매", "신풍", 1),
            new Graph.Edge("신풍", "대림", 1),
            new Graph.Edge("대림", "남구로", 1),
            new Graph.Edge("남구로", "가산디지털단지", 1),
            new Graph.Edge("가산디지털단지", "철산", 1),
            new Graph.Edge("철산", "광명사거리", 1),
            new Graph.Edge("광명사거리", "천왕", 1),
            new Graph.Edge("천왕", "온수", 1),
            new Graph.Edge("온수", "까치울", 1),
            new Graph.Edge("까치울", "부천종합운동장", 1),
            new Graph.Edge("부천종합운동장", "춘의", 1),
            new Graph.Edge("춘의", "신중동", 1),
            new Graph.Edge("신중동", "부천시청", 1),
            new Graph.Edge("부천시청", "상동", 1),
            new Graph.Edge("상동", "삼산체육관", 1),
            new Graph.Edge("삼산체육관", "굴포천", 1),
            new Graph.Edge("굴포천", "부평구청", 1),
            new Graph.Edge("부평구청", "산곡", 1),
            new Graph.Edge("산곡", "석남", 1),
            new Graph.Edge("도봉산", "장암", 1),
            new Graph.Edge("수락산", "도봉산", 1),
            new Graph.Edge("마들", "수락산", 1),
            new Graph.Edge("노원", "마들", 1),
            new Graph.Edge("중계", "노원", 1),
            new Graph.Edge("하계", "중계", 1),
            new Graph.Edge("공릉", "하계", 1),
            new Graph.Edge("태릉입구", "공릉", 1),
            new Graph.Edge("먹골", "태릉입구", 1),
            new Graph.Edge("중화", "먹골", 1),
            new Graph.Edge("상봉", "중화", 1),
            new Graph.Edge("면목", "상봉", 1),
            new Graph.Edge("사가정", "면목", 1),
            new Graph.Edge("용마산", "사가정", 1),
            new Graph.Edge("중곡", "용마산", 1),
            new Graph.Edge("군자", "중곡", 1),
            new Graph.Edge("어린이대공원", "군자", 1),
            new Graph.Edge("건대입구", "어린이대공원", 1),
            new Graph.Edge("뚝섬유원지", "건대입구", 1),
            new Graph.Edge("청담", "뚝섬유원지", 1),
            new Graph.Edge("강남구청", "청담", 1),
            new Graph.Edge("학동", "강남구청", 1),
            new Graph.Edge("논현", "학동", 1),
            new Graph.Edge("반포", "논현", 1),
            new Graph.Edge("고속터미널", "반포", 1),
            new Graph.Edge("내방", "고속터미널", 1),
            new Graph.Edge("이수", "내방", 1),
            new Graph.Edge("남성", "이수", 1),
            new Graph.Edge("숭실대입구", "남성", 1),
            new Graph.Edge("상도", "숭실대입구", 1),
            new Graph.Edge("장승배기", "상도", 1),
            new Graph.Edge("신대방삼거리", "장승배기", 1),
            new Graph.Edge("보라매", "신대방삼거리", 1),
            new Graph.Edge("신풍", "보라매", 1),
            new Graph.Edge("대림", "신풍", 1),
            new Graph.Edge("남구로", "대림", 1),
            new Graph.Edge("가산디지털단지", "남구로", 1),
            new Graph.Edge("철산", "가산디지털단지", 1),
            new Graph.Edge("광명사거리", "철산", 1),
            new Graph.Edge("천왕", "광명사거리", 1),
            new Graph.Edge("온수", "천왕", 1),
            new Graph.Edge("까치울", "온수", 1),
            new Graph.Edge("부천종합운동장", "까치울", 1),
            new Graph.Edge("춘의", "부천종합운동장", 1),
            new Graph.Edge("신중동", "춘의", 1),
            new Graph.Edge("부천시청", "신중동", 1),
            new Graph.Edge("상동", "부천시청", 1),
            new Graph.Edge("삼산체육관", "상동", 1),
            new Graph.Edge("굴포천", "삼산체육관", 1),
            new Graph.Edge("부평구청", "굴포천", 1),
            new Graph.Edge("산곡", "부평구청", 1),
            new Graph.Edge("석남", "산곡", 1),
            new Graph.Edge("암사", "천호", 1),
            new Graph.Edge("천호", "강동구청", 1),
            new Graph.Edge("강동구청", "몽촌토성", 1),
            new Graph.Edge("몽촌토성", "잠실", 1),
            new Graph.Edge("잠실", "석촌", 1),
            new Graph.Edge("석촌", "송파", 1),
            new Graph.Edge("송파", "가락시장", 1),
            new Graph.Edge("가락시장", "문정", 1),
            new Graph.Edge("문정", "장지", 1),
            new Graph.Edge("장지", "복정", 1),
            new Graph.Edge("복정", "남위례", 1),
            new Graph.Edge("남위례", "산성", 1),
            new Graph.Edge("산성", "남한산성입구", 1),
            new Graph.Edge("남한산성입구", "단대오거리", 1),
            new Graph.Edge("단대오거리", "신흥", 1),
            new Graph.Edge("신흥", "수진", 1),
            new Graph.Edge("수진", "모란", 1),
            new Graph.Edge("천호", "암사", 1),
            new Graph.Edge("강동구청", "천호", 1),
            new Graph.Edge("몽촌토성", "강동구청", 1),
            new Graph.Edge("잠실", "몽촌토성", 1),
            new Graph.Edge("석촌", "잠실", 1),
            new Graph.Edge("송파", "석촌", 1),
            new Graph.Edge("가락시장", "송파", 1),
            new Graph.Edge("문정", "가락시장", 1),
            new Graph.Edge("장지", "문정", 1),
            new Graph.Edge("복정", "장지", 1),
            new Graph.Edge("남위례", "복정", 1),
            new Graph.Edge("산성", "남위례", 1),
            new Graph.Edge("남한산성입구", "산성", 1),
            new Graph.Edge("단대오거리", "남한산성입구", 1),
            new Graph.Edge("신흥", "단대오거리", 1),
            new Graph.Edge("수진", "신흥", 1),
            new Graph.Edge("모란", "수진", 1),
            new Graph.Edge("개화", "김포공항", 1),
            new Graph.Edge("김포공항", "공항시장", 1),
            new Graph.Edge("공항시장", "신방화", 1),
            new Graph.Edge("신방화", "마곡나루", 1),
            new Graph.Edge("마곡나루", "양천향교", 1),
            new Graph.Edge("양천향교", "가양", 1),
            new Graph.Edge("가양", "증미", 1),
            new Graph.Edge("증미", "등촌", 1),
            new Graph.Edge("등촌", "염창", 1),
            new Graph.Edge("염창", "신목동", 1),
            new Graph.Edge("신목동", "선유도", 1),
            new Graph.Edge("선유도", "당산", 1),
            new Graph.Edge("당산", "국회의사당", 1),
            new Graph.Edge("국회의사당", "여의도", 1),
            new Graph.Edge("여의도", "샛강", 1),
            new Graph.Edge("샛강", "노량진", 1),
            new Graph.Edge("노량진", "노들", 1),
            new Graph.Edge("노들", "흑석", 1),
            new Graph.Edge("흑석", "동작", 1),
            new Graph.Edge("동작", "구반포", 1),
            new Graph.Edge("구반포", "신반포", 1),
            new Graph.Edge("신반포", "고속터미널", 1),
            new Graph.Edge("고속터미널", "사평", 1),
            new Graph.Edge("사평", "신논현", 1),
            new Graph.Edge("신논현", "언주", 1),
            new Graph.Edge("언주", "선정릉", 1),
            new Graph.Edge("선정릉", "삼성중앙", 1),
            new Graph.Edge("삼성중앙", "봉은사", 1),
            new Graph.Edge("봉은사", "종합운동장", 1),
            new Graph.Edge("종합운동장", "삼전", 1),
            new Graph.Edge("삼전", "석촌고분", 1),
            new Graph.Edge("석촌고분", "석촌", 1),
            new Graph.Edge("석촌", "송파나루", 1),
            new Graph.Edge("송파나루", "한성백제", 1),
            new Graph.Edge("한성백제", "올림픽공원", 1),
            new Graph.Edge("올림픽공원", "둔촌오륜", 1),
            new Graph.Edge("둔촌오륜", "중앙보훈병원", 1),
            new Graph.Edge("김포공항", "개화", 1),
            new Graph.Edge("공항시장", "김포공항", 1),
            new Graph.Edge("신방화", "공항시장", 1),
            new Graph.Edge("마곡나루", "신방화", 1),
            new Graph.Edge("양천향교", "마곡나루", 1),
            new Graph.Edge("가양", "양천향교", 1),
            new Graph.Edge("증미", "가양", 1),
            new Graph.Edge("등촌", "증미", 1),
            new Graph.Edge("염창", "등촌", 1),
            new Graph.Edge("신목동", "염창", 1),
            new Graph.Edge("선유도", "신목동", 1),
            new Graph.Edge("당산", "선유도", 1),
            new Graph.Edge("국회의사당", "당산", 1),
            new Graph.Edge("여의도", "국회의사당", 1),
            new Graph.Edge("샛강", "여의도", 1),
            new Graph.Edge("노량진", "샛강", 1),
            new Graph.Edge("노들", "노량진", 1),
            new Graph.Edge("흑석", "노들", 1),
            new Graph.Edge("동작", "흑석", 1),
            new Graph.Edge("구반포", "동작", 1),
            new Graph.Edge("신반포", "구반포", 1),
            new Graph.Edge("고속터미널", "신반포", 1),
            new Graph.Edge("사평", "고속터미널", 1),
            new Graph.Edge("신논현", "사평", 1),
            new Graph.Edge("언주", "신논현", 1),
            new Graph.Edge("선정릉", "언주", 1),
            new Graph.Edge("삼성중앙", "선정릉", 1),
            new Graph.Edge("봉은사", "삼성중앙", 1),
            new Graph.Edge("종합운동장", "봉은사", 1),
            new Graph.Edge("삼전", "종합운동장", 1),
            new Graph.Edge("석촌고분", "삼전", 1),
            new Graph.Edge("석촌", "석촌고분", 1),
            new Graph.Edge("송파나루", "석촌", 1),
            new Graph.Edge("한성백제", "송파나루", 1),
            new Graph.Edge("올림픽공원", "한성백제", 1),
            new Graph.Edge("둔촌오륜", "올림픽공원", 1),
            new Graph.Edge("중앙보훈병원", "둔촌오륜", 1),
            new Graph.Edge("계양", "귤현", 1),
            new Graph.Edge("귤현", "박촌", 1),
            new Graph.Edge("박촌", "임학", 1),
            new Graph.Edge("임학", "계산", 1),
            new Graph.Edge("계산", "경인교대입구", 1),
            new Graph.Edge("경인교대입구", "작전", 1),
            new Graph.Edge("작전", "갈산", 1),
            new Graph.Edge("갈산", "부평구청", 1),
            new Graph.Edge("부평구청", "부평시장", 1),
            new Graph.Edge("부평시장", "부평", 1),
            new Graph.Edge("부평", "동수", 1),
            new Graph.Edge("동수", "부평삼거리", 1),
            new Graph.Edge("부평삼거리", "간석오거리", 1),
            new Graph.Edge("간석오거리", "인천시청", 1),
            new Graph.Edge("인천시청", "예술회관", 1),
            new Graph.Edge("예술회관", "인천터미널", 1),
            new Graph.Edge("인천터미널", "문학경기장", 1),
            new Graph.Edge("문학경기장", "선학", 1),
            new Graph.Edge("선학", "신연수", 1),
            new Graph.Edge("신연수", "원인재", 1),
            new Graph.Edge("원인재", "동춘", 1),
            new Graph.Edge("동춘", "동막", 1),
            new Graph.Edge("동막", "캠퍼스타운", 1),
            new Graph.Edge("캠퍼스타운", "테크노파크", 1),
            new Graph.Edge("테크노파크", "지식정보단지", 1),
            new Graph.Edge("지식정보단지", "인천대입구", 1),
            new Graph.Edge("인천대입구", "센트럴파크", 1),
            new Graph.Edge("센트럴파크", "국제업무지구", 1),
            new Graph.Edge("국제업무지구", "송도달빛축제공원", 1),
            new Graph.Edge("귤현", "계양", 1),
            new Graph.Edge("박촌", "귤현", 1),
            new Graph.Edge("임학", "박촌", 1),
            new Graph.Edge("계산", "임학", 1),
            new Graph.Edge("경인교대입구", "계산", 1),
            new Graph.Edge("작전", "경인교대입구", 1),
            new Graph.Edge("갈산", "작전", 1),
            new Graph.Edge("부평구청", "갈산", 1),
            new Graph.Edge("부평시장", "부평구청", 1),
            new Graph.Edge("부평", "부평시장", 1),
            new Graph.Edge("동수", "부평", 1),
            new Graph.Edge("부평삼거리", "동수", 1),
            new Graph.Edge("간석오거리", "부평삼거리", 1),
            new Graph.Edge("인천시청", "간석오거리", 1),
            new Graph.Edge("예술회관", "인천시청", 1),
            new Graph.Edge("인천터미널", "예술회관", 1),
            new Graph.Edge("문학경기장", "인천터미널", 1),
            new Graph.Edge("선학", "문학경기장", 1),
            new Graph.Edge("신연수", "선학", 1),
            new Graph.Edge("원인재", "신연수", 1),
            new Graph.Edge("동춘", "원인재", 1),
            new Graph.Edge("동막", "동춘", 1),
            new Graph.Edge("캠퍼스타운", "동막", 1),
            new Graph.Edge("테크노파크", "캠퍼스타운", 1),
            new Graph.Edge("지식정보단지", "테크노파크", 1),
            new Graph.Edge("인천대입구", "지식정보단지", 1),
            new Graph.Edge("센트럴파크", "인천대입구", 1),
            new Graph.Edge("국제업무지구", "센트럴파크", 1),
            new Graph.Edge("송도달빛축제공원", "국제업무지구", 1),
            new Graph.Edge("검단오류", "왕길", 1),
            new Graph.Edge("왕길", "검단사거리", 1),
            new Graph.Edge("검단사거리", "마전", 1),
            new Graph.Edge("마전", "완정", 1),
            new Graph.Edge("완정", "독정", 1),
            new Graph.Edge("독정", "검암", 1),
            new Graph.Edge("검암", "검바위", 1),
            new Graph.Edge("검바위", "아시아드경기장", 1),
            new Graph.Edge("아시아드경기장", "서구청", 1),
            new Graph.Edge("서구청", "가정", 1),
            new Graph.Edge("가정", "가정중앙시장", 1),
            new Graph.Edge("가정중앙시장", "석남", 1),
            new Graph.Edge("석남", "서부여성회관", 1),
            new Graph.Edge("서부여성회관", "인천가좌", 1),
            new Graph.Edge("인천가좌", "가재울", 1),
            new Graph.Edge("가재울", "주안국가산단", 1),
            new Graph.Edge("주안국가산단", "주안", 1),
            new Graph.Edge("주안", "시민공원", 1),
            new Graph.Edge("시민공원", "석바위시장", 1),
            new Graph.Edge("석바위시장", "인천시청", 1),
            new Graph.Edge("인천시청", "석천사거리", 1),
            new Graph.Edge("석천사거리", "모래내시장", 1),
            new Graph.Edge("모래내시장", "만수", 1),
            new Graph.Edge("만수", "남동구청", 1),
            new Graph.Edge("남동구청", "인천대공원", 1),
            new Graph.Edge("인천대공원", "운연", 1),
            new Graph.Edge("왕길", "검단오류", 1),
            new Graph.Edge("검단사거리", "왕길", 1),
            new Graph.Edge("마전", "검단사거리", 1),
            new Graph.Edge("완정", "마전", 1),
            new Graph.Edge("독정", "완정", 1),
            new Graph.Edge("검암", "독정", 1),
            new Graph.Edge("검바위", "검암", 1),
            new Graph.Edge("아시아드경기장", "검바위", 1),
            new Graph.Edge("서구청", "아시아드경기장", 1),
            new Graph.Edge("가정", "서구청", 1),
            new Graph.Edge("가정중앙시장", "가정", 1),
            new Graph.Edge("석남", "가정중앙시장", 1),
            new Graph.Edge("서부여성회관", "석남", 1),
            new Graph.Edge("인천가좌", "서부여성회관", 1),
            new Graph.Edge("가재울", "인천가좌", 1),
            new Graph.Edge("주안국가산단", "가재울", 1),
            new Graph.Edge("주안", "주안국가산단", 1),
            new Graph.Edge("시민공원", "주안", 1),
            new Graph.Edge("석바위시장", "시민공원", 1),
            new Graph.Edge("인천시청", "석바위시장", 1),
            new Graph.Edge("석천사거리", "인천시청", 1),
            new Graph.Edge("모래내시장", "석천사거리", 1),
            new Graph.Edge("만수", "모래내시장", 1),
            new Graph.Edge("남동구청", "만수", 1),
            new Graph.Edge("인천대공원", "남동구청", 1),
            new Graph.Edge("운연", "인천대공원", 1),
            new Graph.Edge("청량리", "왕십리", 1),
            new Graph.Edge("왕십리", "서울숲", 1),
            new Graph.Edge("서울숲", "압구정로데오", 1),
            new Graph.Edge("압구정로데오", "강남구청", 1),
            new Graph.Edge("강남구청", "선정릉", 1),
            new Graph.Edge("선정릉", "선릉", 1),
            new Graph.Edge("선릉", "한티", 1),
            new Graph.Edge("한티", "도곡", 1),
            new Graph.Edge("도곡", "구룡", 1),
            new Graph.Edge("구룡", "개포동", 1),
            new Graph.Edge("개포동", "대모산입구", 1),
            new Graph.Edge("대모산입구", "수서", 1),
            new Graph.Edge("수서", "복정", 1),
            new Graph.Edge("복정", "가천대", 1),
            new Graph.Edge("가천대", "태평", 1),
            new Graph.Edge("태평", "모란", 1),
            new Graph.Edge("모란", "야탑", 1),
            new Graph.Edge("야탑", "이매", 1),
            new Graph.Edge("이매", "서현", 1),
            new Graph.Edge("서현", "수내", 1),
            new Graph.Edge("수내", "정자", 1),
            new Graph.Edge("정자", "미금", 1),
            new Graph.Edge("미금", "오리", 1),
            new Graph.Edge("오리", "죽전", 1),
            new Graph.Edge("죽전", "보정", 1),
            new Graph.Edge("보정", "구성", 1),
            new Graph.Edge("구성", "신갈", 1),
            new Graph.Edge("신갈", "기흥", 1),
            new Graph.Edge("기흥", "상갈", 1),
            new Graph.Edge("상갈", "청명", 1),
            new Graph.Edge("청명", "영통", 1),
            new Graph.Edge("영통", "망포", 1),
            new Graph.Edge("망포", "매탄권선", 1),
            new Graph.Edge("매탄권선", "수원시청", 1),
            new Graph.Edge("수원시청", "매교", 1),
            new Graph.Edge("매교", "수원", 1),
            new Graph.Edge("수원", "고색", 1),
            new Graph.Edge("고색", "오목천", 1),
            new Graph.Edge("오목천", "어천", 1),
            new Graph.Edge("어천", "야목", 1),
            new Graph.Edge("야목", "사리", 1),
            new Graph.Edge("사리", "한대앞", 1),
            new Graph.Edge("한대앞", "중앙", 1),
            new Graph.Edge("중앙", "고잔", 1),
            new Graph.Edge("고잔", "초지", 1),
            new Graph.Edge("초지", "안산", 1),
            new Graph.Edge("안산", "신길온천", 1),
            new Graph.Edge("신길온천", "정왕", 1),
            new Graph.Edge("정왕", "오이도", 1),
            new Graph.Edge("오이도", "달월", 1),
            new Graph.Edge("달월", "월곶", 1),
            new Graph.Edge("월곶", "소래포구", 1),
            new Graph.Edge("소래포구", "인천논현", 1),
            new Graph.Edge("인천논현", "호구포", 1),
            new Graph.Edge("호구포", "남동인더스파크", 1),
            new Graph.Edge("남동인더스파크", "원인재", 1),
            new Graph.Edge("원인재", "연수", 1),
            new Graph.Edge("연수", "송도", 1),
            new Graph.Edge("송도", "인하대", 1),
            new Graph.Edge("인하대", "숭의", 1),
            new Graph.Edge("숭의", "신포", 1),
            new Graph.Edge("신포", "인천", 1),
            new Graph.Edge("왕십리", "청량리", 1),
            new Graph.Edge("서울숲", "왕십리", 1),
            new Graph.Edge("압구정로데오", "서울숲", 1),
            new Graph.Edge("강남구청", "압구정로데오", 1),
            new Graph.Edge("선정릉", "강남구청", 1),
            new Graph.Edge("선릉", "선정릉", 1),
            new Graph.Edge("한티", "선릉", 1),
            new Graph.Edge("도곡", "한티", 1),
            new Graph.Edge("구룡", "도곡", 1),
            new Graph.Edge("개포동", "구룡", 1),
            new Graph.Edge("대모산입구", "개포동", 1),
            new Graph.Edge("수서", "대모산입구", 1),
            new Graph.Edge("복정", "수서", 1),
            new Graph.Edge("가천대", "복정", 1),
            new Graph.Edge("태평", "가천대", 1),
            new Graph.Edge("모란", "태평", 1),
            new Graph.Edge("야탑", "모란", 1),
            new Graph.Edge("이매", "야탑", 1),
            new Graph.Edge("서현", "이매", 1),
            new Graph.Edge("수내", "서현", 1),
            new Graph.Edge("정자", "수내", 1),
            new Graph.Edge("미금", "정자", 1),
            new Graph.Edge("오리", "미금", 1),
            new Graph.Edge("죽전", "오리", 1),
            new Graph.Edge("보정", "죽전", 1),
            new Graph.Edge("구성", "보정", 1),
            new Graph.Edge("신갈", "구성", 1),
            new Graph.Edge("기흥", "신갈", 1),
            new Graph.Edge("상갈", "기흥", 1),
            new Graph.Edge("청명", "상갈", 1),
            new Graph.Edge("영통", "청명", 1),
            new Graph.Edge("망포", "영통", 1),
            new Graph.Edge("매탄권선", "망포", 1),
            new Graph.Edge("수원시청", "매탄권선", 1),
            new Graph.Edge("매교", "수원시청", 1),
            new Graph.Edge("수원", "매교", 1),
            new Graph.Edge("고색", "수원", 1),
            new Graph.Edge("오목천", "고색", 1),
            new Graph.Edge("어천", "오목천", 1),
            new Graph.Edge("야목", "어천", 1),
            new Graph.Edge("사리", "야목", 1),
            new Graph.Edge("한대앞", "사리", 1),
            new Graph.Edge("중앙", "한대앞", 1),
            new Graph.Edge("고잔", "중앙", 1),
            new Graph.Edge("초지", "고잔", 1),
            new Graph.Edge("안산", "초지", 1),
            new Graph.Edge("신길온천", "안산", 1),
            new Graph.Edge("정왕", "신길온천", 1),
            new Graph.Edge("오이도", "정왕", 1),
            new Graph.Edge("달월", "오이도", 1),
            new Graph.Edge("월곶", "달월", 1),
            new Graph.Edge("소래포구", "월곶", 1),
            new Graph.Edge("인천논현", "소래포구", 1),
            new Graph.Edge("호구포", "인천논현", 1),
            new Graph.Edge("남동인더스파크", "호구포", 1),
            new Graph.Edge("원인재", "남동인더스파크", 1),
            new Graph.Edge("연수", "원인재", 1),
            new Graph.Edge("송도", "연수", 1),
            new Graph.Edge("인하대", "송도", 1),
            new Graph.Edge("숭의", "인하대", 1),
            new Graph.Edge("신포", "숭의", 1),
            new Graph.Edge("인천", "신포", 1),
            new Graph.Edge("신사", "논현", 1),
            new Graph.Edge("논현", "신논현", 1),
            new Graph.Edge("신논현", "강남", 1),
            new Graph.Edge("강남", "양재", 1),
            new Graph.Edge("양재", "양재시민의숲", 1),
            new Graph.Edge("양재시민의숲", "청계산입구", 1),
            new Graph.Edge("청계산입구", "판교", 1),
            new Graph.Edge("판교", "정자", 1),
            new Graph.Edge("정자", "미금", 1),
            new Graph.Edge("미금", "동천", 1),
            new Graph.Edge("동천", "수지구청", 1),
            new Graph.Edge("수지구청", "성복", 1),
            new Graph.Edge("성복", "상현", 1),
            new Graph.Edge("상현", "광교중앙", 1),
            new Graph.Edge("광교중앙", "광교", 1),
            new Graph.Edge("논현", "신사", 1),
            new Graph.Edge("신논현", "논현", 1),
            new Graph.Edge("강남", "신논현", 1),
            new Graph.Edge("양재", "강남", 1),
            new Graph.Edge("양재시민의숲", "양재", 1),
            new Graph.Edge("청계산입구", "양재시민의숲", 1),
            new Graph.Edge("판교", "청계산입구", 1),
            new Graph.Edge("정자", "판교", 1),
            new Graph.Edge("미금", "정자", 1),
            new Graph.Edge("동천", "미금", 1),
            new Graph.Edge("수지구청", "동천", 1),
            new Graph.Edge("성복", "수지구청", 1),
            new Graph.Edge("상현", "성복", 1),
            new Graph.Edge("광교중앙", "상현", 1),
            new Graph.Edge("광교", "광교중앙", 1),
            new Graph.Edge("공덕", "효창공원앞", 1),
            new Graph.Edge("서강대", "공덕", 1),
            new Graph.Edge("홍대입구", "서강대", 1),
            new Graph.Edge("가좌", "홍대입구", 1),
            new Graph.Edge("디지털미디어시티", "가좌", 1),
            new Graph.Edge("수색", "디지털미디어시티", 1),
            new Graph.Edge("화전", "수색", 1),
            new Graph.Edge("강매", "화전", 1),
            new Graph.Edge("행신", "강매", 1),
            new Graph.Edge("능곡", "행신", 1),
            new Graph.Edge("대곡", "능곡", 1),
            new Graph.Edge("곡산", "대곡", 1),
            new Graph.Edge("백마", "곡산", 1),
            new Graph.Edge("풍산", "백마", 1),
            new Graph.Edge("일산", "풍산", 1),
            new Graph.Edge("탄현", "일산", 1),
            new Graph.Edge("야당", "탄현", 1),
            new Graph.Edge("운정", "야당", 1),
            new Graph.Edge("금릉", "운정", 1),
            new Graph.Edge("금촌", "금릉", 1),
            new Graph.Edge("월롱", "금촌", 1),
            new Graph.Edge("파주", "월롱", 1),
            new Graph.Edge("문산", "파주", 1),
            new Graph.Edge("운천", "문산", 1),
            new Graph.Edge("임진강", "운천", 1),
            new Graph.Edge("가좌", "신촌", 1),
            new Graph.Edge("신촌", "서울역", 1),
            new Graph.Edge("효창공원앞", "용산", 1),
            new Graph.Edge("용산", "이촌", 1),
            new Graph.Edge("이촌", "서빙고", 1),
            new Graph.Edge("서빙고", "한남", 1),
            new Graph.Edge("한남", "옥수", 1),
            new Graph.Edge("옥수", "응봉", 1),
            new Graph.Edge("응봉", "왕십리", 1),
            new Graph.Edge("왕십리", "청량리", 1),
            new Graph.Edge("청량리", "회기", 1),
            new Graph.Edge("회기", "중랑", 1),
            new Graph.Edge("중랑", "상봉", 1),
            new Graph.Edge("상봉", "망우", 1),
            new Graph.Edge("망우", "양원", 1),
            new Graph.Edge("양원", "구리", 1),
            new Graph.Edge("구리", "도농", 1),
            new Graph.Edge("도농", "양정", 1),
            new Graph.Edge("양정", "덕소", 1),
            new Graph.Edge("덕소", "도심", 1),
            new Graph.Edge("도심", "팔당", 1),
            new Graph.Edge("팔당", "운길산", 1),
            new Graph.Edge("운길산", "양수", 1),
            new Graph.Edge("양수", "신원", 1),
            new Graph.Edge("신원", "국수", 1),
            new Graph.Edge("국수", "아신", 1),
            new Graph.Edge("아신", "오빈", 1),
            new Graph.Edge("오빈", "양평", 1),
            new Graph.Edge("양평", "원덕", 1),
            new Graph.Edge("원덕", "용문", 1),
            new Graph.Edge("용문", "지평", 1),
            new Graph.Edge("효창공원앞", "공덕", 1),
            new Graph.Edge("공덕", "서강대", 1),
            new Graph.Edge("서강대", "홍대입구", 1),
            new Graph.Edge("홍대입구", "가좌", 1),
            new Graph.Edge("가좌", "디지털미디어시티", 1),
            new Graph.Edge("디지털미디어시티", "수색", 1),
            new Graph.Edge("수색", "화전", 1),
            new Graph.Edge("화전", "강매", 1),
            new Graph.Edge("강매", "행신", 1),
            new Graph.Edge("행신", "능곡", 1),
            new Graph.Edge("능곡", "대곡", 1),
            new Graph.Edge("대곡", "곡산", 1),
            new Graph.Edge("곡산", "백마", 1),
            new Graph.Edge("백마", "풍산", 1),
            new Graph.Edge("풍산", "일산", 1),
            new Graph.Edge("일산", "탄현", 1),
            new Graph.Edge("탄현", "야당", 1),
            new Graph.Edge("야당", "운정", 1),
            new Graph.Edge("운정", "금릉", 1),
            new Graph.Edge("금릉", "금촌", 1),
            new Graph.Edge("금촌", "월롱", 1),
            new Graph.Edge("월롱", "파주", 1),
            new Graph.Edge("파주", "문산", 1),
            new Graph.Edge("문산", "운천", 1),
            new Graph.Edge("운천", "임진강", 1),
            new Graph.Edge("신촌", "가좌", 1),
            new Graph.Edge("서울역", "신촌", 1),
            new Graph.Edge("용산", "효창공원앞", 1),
            new Graph.Edge("이촌", "용산", 1),
            new Graph.Edge("서빙고", "이촌", 1),
            new Graph.Edge("한남", "서빙고", 1),
            new Graph.Edge("옥수", "한남", 1),
            new Graph.Edge("응봉", "옥수", 1),
            new Graph.Edge("왕십리", "응봉", 1),
            new Graph.Edge("청량리", "왕십리", 1),
            new Graph.Edge("회기", "청량리", 1),
            new Graph.Edge("중랑", "회기", 1),
            new Graph.Edge("상봉", "중랑", 1),
            new Graph.Edge("망우", "상봉", 1),
            new Graph.Edge("양원", "망우", 1),
            new Graph.Edge("구리", "양원", 1),
            new Graph.Edge("도농", "구리", 1),
            new Graph.Edge("양정", "도농", 1),
            new Graph.Edge("덕소", "양정", 1),
            new Graph.Edge("도심", "덕소", 1),
            new Graph.Edge("팔당", "도심", 1),
            new Graph.Edge("운길산", "팔당", 1),
            new Graph.Edge("양수", "운길산", 1),
            new Graph.Edge("신원", "양수", 1),
            new Graph.Edge("국수", "신원", 1),
            new Graph.Edge("아신", "국수", 1),
            new Graph.Edge("오빈", "아신", 1),
            new Graph.Edge("양평", "오빈", 1),
            new Graph.Edge("원덕", "양평", 1),
            new Graph.Edge("용문", "원덕", 1),
            new Graph.Edge("지평", "용문", 1),
            new Graph.Edge("서울역", "공덕", 1),
            new Graph.Edge("공덕", "홍대입구", 1),
            new Graph.Edge("홍대입구", "디지털미디어시티", 1),
            new Graph.Edge("디지털미디어시티", "마곡나루", 1),
            new Graph.Edge("마곡나루", "김포공항", 1),
            new Graph.Edge("김포공항", "계양", 1),
            new Graph.Edge("계양", "검암", 1),
            new Graph.Edge("검암", "청라국제도시", 1),
            new Graph.Edge("청라국제도시", "영종", 1),
            new Graph.Edge("영종", "운서", 1),
            new Graph.Edge("운서", "공항화물청사", 1),
            new Graph.Edge("공항화물청사", "인천공항1터미널", 1),
            new Graph.Edge("인천공항1터미널", "인천공항2터미널", 1),
            new Graph.Edge("공덕", "서울역", 1),
            new Graph.Edge("홍대입구", "공덕", 1),
            new Graph.Edge("디지털미디어시티", "홍대입구", 1),
            new Graph.Edge("마곡나루", "디지털미디어시티", 1),
            new Graph.Edge("김포공항", "마곡나루", 1),
            new Graph.Edge("계양", "김포공항", 1),
            new Graph.Edge("검암", "계양", 1),
            new Graph.Edge("청라국제도시", "검암", 1),
            new Graph.Edge("영종", "청라국제도시", 1),
            new Graph.Edge("운서", "영종", 1),
            new Graph.Edge("공항화물청사", "운서", 1),
            new Graph.Edge("인천공항1터미널", "공항화물청사", 1),
            new Graph.Edge("인천공항2터미널", "인천공항1터미널", 1),
            new Graph.Edge("광운대", "상봉", 1),
            new Graph.Edge("청량리", "회기", 1),
            new Graph.Edge("회기", "중랑", 1),
            new Graph.Edge("중랑", "상봉", 1),
            new Graph.Edge("상봉", "망우", 1),
            new Graph.Edge("망우", "신내", 1),
            new Graph.Edge("신내", "갈매", 1),
            new Graph.Edge("갈매", "별내", 1),
            new Graph.Edge("별내", "퇴계원", 1),
            new Graph.Edge("퇴계원", "사릉", 1),
            new Graph.Edge("사릉", "금곡", 1),
            new Graph.Edge("금곡", "평내호평", 1),
            new Graph.Edge("평내호평", "천마산", 1),
            new Graph.Edge("천마산", "마석", 1),
            new Graph.Edge("마석", "대성리", 1),
            new Graph.Edge("대성리", "청평", 1),
            new Graph.Edge("청평", "상천", 1),
            new Graph.Edge("상천", "가평", 1),
            new Graph.Edge("가평", "굴봉산", 1),
            new Graph.Edge("굴봉산", "백양리", 1),
            new Graph.Edge("백양리", "강촌", 1),
            new Graph.Edge("강촌", "김유정", 1),
            new Graph.Edge("김유정", "남춘천", 1),
            new Graph.Edge("남춘천", "춘천", 1),
            new Graph.Edge("상봉", "광운대", 1),
            new Graph.Edge("회기", "청량리", 1),
            new Graph.Edge("중랑", "회기", 1),
            new Graph.Edge("상봉", "중랑", 1),
            new Graph.Edge("망우", "상봉", 1),
            new Graph.Edge("신내", "망우", 1),
            new Graph.Edge("갈매", "신내", 1),
            new Graph.Edge("별내", "갈매", 1),
            new Graph.Edge("퇴계원", "별내", 1),
            new Graph.Edge("사릉", "퇴계원", 1),
            new Graph.Edge("금곡", "사릉", 1),
            new Graph.Edge("평내호평", "금곡", 1),
            new Graph.Edge("천마산", "평내호평", 1),
            new Graph.Edge("마석", "천마산", 1),
            new Graph.Edge("대성리", "마석", 1),
            new Graph.Edge("청평", "대성리", 1),
            new Graph.Edge("상천", "청평", 1),
            new Graph.Edge("가평", "상천", 1),
            new Graph.Edge("굴봉산", "가평", 1),
            new Graph.Edge("백양리", "굴봉산", 1),
            new Graph.Edge("강촌", "백양리", 1),
            new Graph.Edge("김유정", "강촌", 1),
            new Graph.Edge("남춘천", "김유정", 1),
            new Graph.Edge("춘천", "남춘천", 1),
            new Graph.Edge("발곡", "회룡", 1),
            new Graph.Edge("회룡", "범골", 1),
            new Graph.Edge("범골", "경전철의정부", 1),
            new Graph.Edge("경전철의정부", "의정부시청", 1),
            new Graph.Edge("의정부시청", "흥선", 1),
            new Graph.Edge("흥선", "의정부중앙", 1),
            new Graph.Edge("의정부중앙", "동오", 1),
            new Graph.Edge("동오", "새말", 1),
            new Graph.Edge("새말", "경기도청북부청사", 1),
            new Graph.Edge("경기도청북부청사", "효자", 1),
            new Graph.Edge("효자", "곤제", 1),
            new Graph.Edge("곤제", "어룡", 1),
            new Graph.Edge("어룡", "송산", 1),
            new Graph.Edge("송산", "탑석", 1),
            new Graph.Edge("회룡", "발곡", 1),
            new Graph.Edge("범골", "회룡", 1),
            new Graph.Edge("경전철의정부", "범골", 1),
            new Graph.Edge("의정부시청", "경전철의정부", 1),
            new Graph.Edge("흥선", "의정부시청", 1),
            new Graph.Edge("의정부중앙", "흥선", 1),
            new Graph.Edge("동오", "의정부중앙", 1),
            new Graph.Edge("새말", "동오", 1),
            new Graph.Edge("경기도청북부청사", "새말", 1),
            new Graph.Edge("효자", "경기도청북부청사", 1),
            new Graph.Edge("곤제", "효자", 1),
            new Graph.Edge("어룡", "곤제", 1),
            new Graph.Edge("송산", "어룡", 1),
            new Graph.Edge("탑석", "송산", 1),
            new Graph.Edge("기흥", "강남대", 1),
            new Graph.Edge("강남대", "지석", 1),
            new Graph.Edge("지석", "어정", 1),
            new Graph.Edge("어정", "동백", 1),
            new Graph.Edge("동백", "초당", 1),
            new Graph.Edge("초당", "삼가", 1),
            new Graph.Edge("삼가", "시청.용인대", 1),
            new Graph.Edge("시청.용인대", "명지대", 1),
            new Graph.Edge("명지대", "김량장", 1),
            new Graph.Edge("김량장", "운동장.송담대", 1),
            new Graph.Edge("운동장.송담대", "고진", 1),
            new Graph.Edge("고진", "보평", 1),
            new Graph.Edge("보평", "둔전", 1),
            new Graph.Edge("둔전", "전대.에버랜드", 1),
            new Graph.Edge("강남대", "기흥", 1),
            new Graph.Edge("지석", "강남대", 1),
            new Graph.Edge("어정", "지석", 1),
            new Graph.Edge("동백", "어정", 1),
            new Graph.Edge("초당", "동백", 1),
            new Graph.Edge("삼가", "초당", 1),
            new Graph.Edge("시청.용인대", "삼가", 1),
            new Graph.Edge("명지대", "시청.용인대", 1),
            new Graph.Edge("김량장", "명지대", 1),
            new Graph.Edge("운동장.송담대", "김량장", 1),
            new Graph.Edge("고진", "운동장.송담대", 1),
            new Graph.Edge("보평", "고진", 1),
            new Graph.Edge("둔전", "보평", 1),
            new Graph.Edge("전대.에버랜드", "둔전", 1),
            new Graph.Edge("판교", "이매", 1),
            new Graph.Edge("이매", "삼동", 1),
            new Graph.Edge("삼동", "경기광주", 1),
            new Graph.Edge("경기광주", "초월", 1),
            new Graph.Edge("초월", "곤지암", 1),
            new Graph.Edge("곤지암", "신둔도예촌", 1),
            new Graph.Edge("신둔도예촌", "이천", 1),
            new Graph.Edge("이천", "부발", 1),
            new Graph.Edge("부발", "세종대왕릉", 1),
            new Graph.Edge("세종대왕릉", "여주", 1),
            new Graph.Edge("이매", "판교", 1),
            new Graph.Edge("삼동", "이매", 1),
            new Graph.Edge("경기광주", "삼동", 1),
            new Graph.Edge("초월", "경기광주", 1),
            new Graph.Edge("곤지암", "초월", 1),
            new Graph.Edge("신둔도예촌", "곤지암", 1),
            new Graph.Edge("이천", "신둔도예촌", 1),
            new Graph.Edge("부발", "이천", 1),
            new Graph.Edge("세종대왕릉", "부발", 1),
            new Graph.Edge("여주", "세종대왕릉", 1),
            new Graph.Edge("북한산우이", "솔밭공원", 1),
            new Graph.Edge("솔밭공원", "4·19민주묘지", 1),
            new Graph.Edge("4·19민주묘지", "가오리", 1),
            new Graph.Edge("가오리", "화계", 1),
            new Graph.Edge("화계", "삼양", 1),
            new Graph.Edge("삼양", "삼양사거리", 1),
            new Graph.Edge("삼양사거리", "솔샘", 1),
            new Graph.Edge("솔샘", "북한산보국문", 1),
            new Graph.Edge("북한산보국문", "정릉", 1),
            new Graph.Edge("정릉", "성신여대입구", 1),
            new Graph.Edge("성신여대입구", "보문", 1),
            new Graph.Edge("보문", "신설동", 1),
            new Graph.Edge("솔밭공원", "북한산우이", 1),
            new Graph.Edge("4·19민주묘지", "솔밭공원", 1),
            new Graph.Edge("가오리", "4·19민주묘지", 1),
            new Graph.Edge("화계", "가오리", 1),
            new Graph.Edge("삼양", "화계", 1),
            new Graph.Edge("삼양사거리", "삼양", 1),
            new Graph.Edge("솔샘", "삼양사거리", 1),
            new Graph.Edge("북한산보국문", "솔샘", 1),
            new Graph.Edge("정릉", "북한산보국문", 1),
            new Graph.Edge("성신여대입구", "정릉", 1),
            new Graph.Edge("보문", "성신여대입구", 1),
            new Graph.Edge("신설동", "보문", 1),
            new Graph.Edge("소사", "소새울", 1),
            new Graph.Edge("소새울", "시흥대야", 1),
            new Graph.Edge("시흥대야", "신천", 1),
            new Graph.Edge("신천", "신현", 1),
            new Graph.Edge("신현", "시흥시청", 1),
            new Graph.Edge("시흥시청", "시흥능곡", 1),
            new Graph.Edge("시흥능곡", "달미", 1),
            new Graph.Edge("달미", "선부", 1),
            new Graph.Edge("선부", "초지", 1),
            new Graph.Edge("초지", "시우", 1),
            new Graph.Edge("시우", "원시", 1),
            new Graph.Edge("소새울", "소사", 1),
            new Graph.Edge("시흥대야", "소새울", 1),
            new Graph.Edge("신천", "시흥대야", 1),
            new Graph.Edge("신현", "신천", 1),
            new Graph.Edge("시흥시청", "신현", 1),
            new Graph.Edge("시흥능곡", "시흥시청", 1),
            new Graph.Edge("달미", "시흥능곡", 1),
            new Graph.Edge("선부", "달미", 1),
            new Graph.Edge("초지", "선부", 1),
            new Graph.Edge("시우", "초지", 1),
            new Graph.Edge("원시", "시우", 1),
            new Graph.Edge("양촌", "구래", 1),
            new Graph.Edge("구래", "마산", 1),
            new Graph.Edge("마산", "장기", 1),
            new Graph.Edge("장기", "운양", 1),
            new Graph.Edge("운양", "걸포북변", 1),
            new Graph.Edge("걸포북변", "사우", 1),
            new Graph.Edge("사우", "풍무", 1),
            new Graph.Edge("풍무", "고촌", 1),
            new Graph.Edge("고촌", "김포공항", 1),
            new Graph.Edge("구래", "양촌", 1),
            new Graph.Edge("마산", "구래", 1),
            new Graph.Edge("장기", "마산", 1),
            new Graph.Edge("운양", "장기", 1),
            new Graph.Edge("걸포북변", "운양", 1),
            new Graph.Edge("사우", "걸포북변", 1),
            new Graph.Edge("풍무", "사우", 1),
            new Graph.Edge("고촌", "풍무", 1),
            new Graph.Edge("김포공항", "고촌", 1),
            new Graph.Edge("샛강", "대방", 1),
            new Graph.Edge("대방", "서울지방병무청", 1),
            new Graph.Edge("서울지방병무청", "보라매", 1),
            new Graph.Edge("보라매", "보라매공원", 1),
            new Graph.Edge("보라매공원", "보라매병원", 1),
            new Graph.Edge("보라매병원", "당곡", 1),
            new Graph.Edge("당곡", "신림", 1),
            new Graph.Edge("신림", "서원", 1),
            new Graph.Edge("서원", "서울대벤처타운", 1),
            new Graph.Edge("서울대벤처타운", "관악산", 1),
            new Graph.Edge("대방", "샛강", 1),
            new Graph.Edge("서울지방병무청", "대방", 1),
            new Graph.Edge("보라매", "서울지방병무청", 1),
            new Graph.Edge("보라매공원", "보라매", 1),
            new Graph.Edge("보라매병원", "보라매공원", 1),
            new Graph.Edge("당곡", "보라매병원", 1),
            new Graph.Edge("신림", "당곡", 1),
            new Graph.Edge("서원", "신림", 1),
            new Graph.Edge("서울대벤처타운", "서원", 1),
            new Graph.Edge("관악산", "서울대벤처타운", 1),
    };
}
